service: mario
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  registerUser:
    handler: src/registerUser.registerUser
    events:
      - httpApi: 
          method: POST
          path: /register
  getUserAll:
    handler: src/getUsers.getUserAll
    events:
      - http:
          method: get
          path: /getUserAll
  getUserId:
    handler: src/getUserId.getUserId
    events:
      - http:
          method: post
          path: /getUserId
  getSwapiPeopleAll:
    handler: src/getSwapiPeopleAll.getSwapiPeopleAll
    events:
      - http:
          method: get
          path: /getSwapiPeopleAll
  getSwapiPeopleId:
    handler: src/getSwapiPeopleId.getSwapiPeopleId
    events:
      - http:
          method: post
          path: /getSwapiPeopleId 

custom:
  esbuild:
    bundle: true
    minify: true
    external:
      - sequelize
      - mysql2
      - pg-hstore 

plugins:
  - serverless-esbuild
  - serverless-offline
